dateModified: 1766464814
email:
  fromEmail: michael@bluth.com
  fromName: Pest
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    7d1a7bf3-c346-48bc-bb77-f7d76fcacf2e: 'Text Field' # Text Field
    8c52290b-5521-4c12-bbee-54097cfdfb5e: 'Public Schema' # Public Schema
    99c2747f-1049-46bc-93e0-424bad0544e5: Pest # Pest
    0193fbbc-6912-4ff6-a3d5-e60ea03c8590: Default # Default
    10199d0e-57f0-4724-aefb-1ef4ed73b408: 'Field Two' # Field Two
    17685ada-d64c-459c-b9fc-678d43e4bee8: 'Dropdown Field' # Dropdown Field
    ae919370-04f6-4e2d-8d42-f255cc1b6a75: Posts # Posts
    b5c238dd-588f-4f0a-b9e4-8a988f0e7468: 'Block Type One' # Block Type One
    b11e9b16-d6b0-4771-86bb-3fe962b4596d: Pest # Pest
    bda4d299-4f91-43c1-91d1-48abd1dd5fb4: Pest # Pest
    bdde35b2-daab-45e7-aef7-43fd8b221aa2: Pest # Pest
    c05f8773-60a8-4f5e-9925-3cc36a064793: 'Field One' # Field One
    c148dfb3-a122-49ed-8538-de26d0482663: 'Entries Field' # Entries Field
    c7529b61-60cd-4e18-a272-3084aee7fa89: 'Matrix Field' # Matrix Field
    f948b9a4-6a4e-43da-84aa-65b91c0cd202: Common # Common
system:
  edition: solo
  live: true
  name: Pest
  schemaVersion: 4.5.3.0
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
