columnSuffix: null
contentColumnType: string
fieldGroup: f948b9a4-6a4e-43da-84aa-65b91c0cd202 # Common
handle: entriesField
instructions: null
name: 'Entries Field'
searchable: false
settings:
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maintainHierarchy: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Entries
